# Generated by Django 2.0.7 on 2020-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('display_order', models.IntegerField()),
                ('name', models.CharField(default='star_road视频社区', max_length=32, verbose_name='视频名称')),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='courses', verbose_name='封面图片')),
                ('vide_url', models.CharField(max_length=1000, verbose_name='视频链接')),
                ('author', models.CharField(default='joab', max_length=32, verbose_name='视频作者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
