# Generated by Django 2.0.7 on 2020-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='up',
            field=models.BigIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
