# Generated by Django 2.0.7 on 2020-08-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='up',
            field=models.BigIntegerField(default=186, verbose_name='点赞数'),
        ),
    ]
