# Generated by Django 2.0.7 on 2020-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200812_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='display_order',
            field=models.IntegerField(verbose_name='排序'),
        ),
    ]
