# Generated by Django 2.0.7 on 2020-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='month_num',
            field=models.CharField(max_length=5, null=True, verbose_name='购买的月数'),
        ),
    ]
