# Generated by Django 2.0.7 on 2020-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_up'),
        ('user', '0003_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collect',
            field=models.ManyToManyField(null=True, to='video.Video'),
        ),
    ]
