# Generated by Django 2.0.7 on 2020-08-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200812_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collect',
            field=models.ManyToManyField(to='video.Video'),
        ),
    ]
