# Generated by Django 2.0.7 on 2020-08-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200812_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BigIntegerField(default=0, verbose_name='会员'),
        ),
    ]
