# Generated by Django 2.0.7 on 2020-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_expire',
            field=models.IntegerField(null=True, verbose_name='会员过期时间'),
        ),
    ]
