# Generated by Django 2.0.7 on 2020-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_vip_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip_expire',
            field=models.FloatField(null=True, verbose_name='会员过期时间'),
        ),
    ]
