# Generated by Django 2.0.7 on 2020-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('display_order', models.IntegerField()),
                ('title', models.CharField(default='妹子图', max_length=32, verbose_name='图片标题')),
                ('img_url', models.ImageField(upload_to='img', verbose_name='妹子图')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
