# Generated by Django 2.0.7 on 2020-08-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(unique=True, upload_to='img', verbose_name='妹子图'),
        ),
    ]
