# Generated by Django 2.0.7 on 2020-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('display_order', models.IntegerField(verbose_name='排序')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('describe', models.CharField(max_length=20, verbose_name='描述')),
                ('heat', models.BigIntegerField(verbose_name='热度')),
                ('is_vip', models.BigIntegerField(default=0, verbose_name='收费')),
                ('film_url', models.CharField(max_length=1000, verbose_name='电影地址')),
                ('img_url', models.CharField(max_length=200, verbose_name='封面地址')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
